from FroggoBot.Modules.autobox import AutoBox
from FroggoBot.Modules.autobuy import AutoBuy
from FroggoBot.Modules.autogift import AutoGift
from FroggoBot.Modules.automoney import AutoMoney
from FroggoBot.Modules.autopizza import AutoPizza
from FroggoBot.Modules.balancecheck import BalanceCheck
from FroggoBot.Modules.beg import Beg
from FroggoBot.Modules.crime import Crime
from FroggoBot.Modules.dig import Dig
from FroggoBot.Modules.fish import Fish
from FroggoBot.Modules.highlow import HighLow
from FroggoBot.Modules.hunt import Hunt
from FroggoBot.Modules.postmeme import PostMeme
from FroggoBot.Modules.scratch import Scratch
from FroggoBot.Modules.search import Search
from FroggoBot.Modules.snakeeyes import SnakeEyes
from FroggoBot.Modules.work import Work